services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_YOUR_HOSTNAME=/api
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/employees
    networks:
      - mern-network

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - mern-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
