version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-service:27017/mydatabase
    networks:
      - mern-network

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
