#Handle incoming requests by listening on port 80(HTTP),
# forward root URL traffic to PLACHODER NAME 'frontend' &
# api URL  traffic to backend PLACEHOLDER NAME 'backend.
server {
    listen 80;

    location / {
        proxy_pass http://frontend-service:3000;
    }

    location /api/ {
        proxy_pass http://backend-service:5000;
    }
}
